### ISSUE TITLE
qrandomunif() returns NA if the range spans all integers, Inf for all floats

### ISSUE THREAD

**Issue by hyginn** [skoestlmeier/qrandom#2]
## Expected Behavior
`qrandomunif(n = 1, a = -.Machine$integer.max, b = .Machine$integer.max)` should return a number.
`qrandomunif(1, -.Machine$double.xmax, .Machine$double.xmax)` should return a number.

i.e.: all valid numbers should be acceptable as input.

## Current Behavior
`qrandomunif(n = 1, a = -.Machine$integer.max, b = .Machine$integer.max)` returns `NA`.
`qrandomunif(1, -.Machine$double.xmax, .Machine$double.xmax)` returns `Inf`.

## Possible Solution
1. Ignore (Edge case)
2. Note limitations on `a` and `b` in the man page
3. Silently modify input: `if (b == -.Machine$integer.max) b <- -(.Machine$integer.max - 1)` works, don't know off the top of my head what to do about the floats.
4. Cast `a` and `b` to mpfr numbers, perform `(b - a) * urand + a` at high resolution and cast `as.numeric()` as the last step.

## Steps to Reproduce (for bugs)
cf. Expected behaviour

## Context
Trying to get maximally dispersed random numbers

## Your Environment
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] qrandom_1.1    testthat_2.0.1

loaded via a namespace (and not attached):
 [1] compiler_3.5.1 magrittr_1.5   R6_2.3.0       tools_3.5.1    gmp_0.5-13.2  
 [6] yaml_2.2.0     curl_3.2       jsonlite_1.6   rlang_0.3.0.1  Rmpfr_0.7-1   
```

**Comment by skoestlmeier** [comment]
Thanks a lot for your detailed and very helpful issue. Your contribution here significantly improves the quality of this package (and also my knowledge of R)!

I just checked your issue and it is reproducible. I have implemented your suggested solution no. 4, i.e. the transformation
`urand <- (b_tmp - a_tmp) * urand + a_tmp`
is now calculated on numbers having mpfr type. Both of your statements in your issues now return a number.
